name: build release

on:
  push:
    branches: [ "build-release" ]
  pull_request:
    branches: [ "build-release" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - uses: noriban/sign-android-release@v5
      name: Sign app APK
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "35.0.0"

    - name: Rename APK    
      run: mv app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/RTranslator.apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: RTranslator
        path: app/build/outputs/apk/release/RTranslator.apk
